/* ═══════════════════════════════════════════════════════════════
   MIGRATION BASELINE GENERATOR
   One-shot helper for adopting versioned migrations on an existing
   database (see docs/DATABASE-MIGRATIONS.md → "Baseline"):

     # Against a shadow/dev database whose schema matches production:
     npx tsx scripts/db-migrate-baseline.ts "initial baseline"

   What it does (against the database pointed at by DATABASE_URL):
   1. Resolves the target database URL (arg --url, else DATABASE_URL).
   2. Uses `prisma migrate diff --from-empty --to-schema-datamodel`
      to produce SQL matching the current prisma/schema.prisma.
   3. Creates prisma/migrations/0_init/migration.sql + migration_lock.toml.
   4. Marks it as applied (`migrate resolve --applied 0_init`) so the
      existing database is NOT altered — future `migrate deploy` runs
      then apply only NEW migrations on top.

   Run it once per environment during the migration adoption window,
   against a database whose schema already matches schema.prisma
   (e.g. the dev database after `prisma db push`).
   ═══════════════════════════════════ tsx-safe (no app imports) ══ */

import { execFileSync } from "child_process";
import { mkdirSync, writeFileSync, rmSync, existsSync } from "fs";
import path from "path";

const PRISMA_CLI = "node_modules/prisma/build/index.js";

function run(args: string[], env?: Record<string, string>): string {
  return execFileSync(process.execPath, [PRISMA_CLI, ...args], {
    stdio: "pipe",
    encoding: "utf8",
    timeout: 120_000,
    env: env ? { ...process.env, ...env } : process.env,
  });
}

function main(): void {
  const args = process.argv.slice(2);
  const nameArgIdx = args.findIndex((a) => !a.startsWith("--"));
  const name =
    nameArgIdx >= 0
      ? args[nameArgIdx]
      : (() => {
          console.error(
            "Usage: npx tsx scripts/db-migrate-baseline.ts \"<name>\" [--url <database-url>]"
          );
          process.exit(1);
        })();

  const urlFlagIdx = args.indexOf("--url");
  const url =
    urlFlagIdx >= 0 ? args[urlFlagIdx + 1] : process.env["DATABASE_URL"];

  if (!url) {
    console.error(
      "No database URL. Pass --url <database-url> or set DATABASE_URL.\n" +
        "The database must ALREADY match prisma/schema.prisma (run `npm run db:push` first)."
    );
    process.exit(1);
  }

  const migrationsDir = path.resolve("prisma/migrations");
  const baselineDir = path.join(migrationsDir, "0_init");

  if (existsSync(baselineDir)) {
    console.error(
      `Refusing to overwrite ${baselineDir}. Delete it first if you really want a new baseline.`
    );
    process.exit(1);
  }

  console.log("→ Generating SQL diff from empty schema…");
  const sql = run([
    "migrate",
    "diff",
    "--from-empty",
    "--to-schema-datamodel",
    "prisma/schema.prisma",
    "--script",
  ]);

  mkdirSync(baselineDir, { recursive: true });
  writeFileSync(path.join(baselineDir, "migration.sql"), sql, "utf8");
  writeFileSync(
    path.join(migrationsDir, "migration_lock.toml"),
    '# Please do not edit this file manually\n# It should be added in your version-control system (i.e. Git)\nprovider = "sqlite"\n',
    "utf8"
  );
  console.log(`✓ Created prisma/migrations/0_init/migration.sql (${sql.split("\n").length} lines)`);

  console.log("→ Marking baseline as applied (no data is changed)…");
  run(["migrate", "resolve", "--applied", "0_init"], { DATABASE_URL: url });
  console.log(
    "✓ Baseline recorded. Future `npm run db:migrate:deploy` runs apply only NEW migrations."
  );
  console.log(
    "\nNext steps:\n" +
      "  1. Commit prisma/migrations/ to version control.\n" +
      "  2. Point DATABASE_URL at production and run `npm run db:migrate:status` to verify.\n" +
      "  3. See docs/DATABASE-MIGRATIONS.md for the full runbook."
  );
}

function cleanupOnFailure(): void {
  try {
    if (existsSync(path.resolve("prisma/migrations/0_init"))) {
      rmSync(path.resolve("prisma/migrations/0_init"), { recursive: true, force: true });
    }
  } catch {
    /* best effort */
  }
}

try {
  main();
} catch (err) {
  console.error(
    "✗ Baseline failed:",
    err instanceof Error ? err.message : String(err)
  );
  cleanupOnFailure();
  process.exit(1);
}
